import { invoke } from "@tauri-apps/api/core";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { type Locale, t } from "../i18n";
import { MarkdownEditor } from "./MarkdownEditor";

type Document = { id: string; documentType: "markdown" | "pdf" | "image"; title: string; markdown?: string };
type Layout = { left: { tabs: string[]; activeTabId: string | null }; right: { tabs: string[]; activeTabId: string | null }; sizes: [number, number, number]; collapsed: [boolean, boolean, boolean] };
type WorkspaceData = { story: { id: string; title: string }; documents: Document[]; workspaceLayoutJson: string };
const fallbackLayout: Layout = { left: { tabs: ["journal"], activeTabId: "journal" }, right: { tabs: [], activeTabId: null }, sizes: [45, 35, 20], collapsed: [false, false, false] };

export function Workspace({ storyId, locale, onExit }: { storyId: string; locale: Locale; onExit: () => void }) {
  const [data, setData] = useState<WorkspaceData>(); const [layout, setLayout] = useState<Layout>(fallbackLayout);
  const [dirty, setDirty] = useState<Record<string, string>>({}); const [saveState, setSaveState] = useState<"idle" | "saving" | "saved" | "error">("idle"); const [findOpen, setFindOpen] = useState(false); const [query, setQuery] = useState("");
  const layoutTimer = useRef<number | undefined>(undefined); const saveTimer = useRef<number | undefined>(undefined);
  const dirtyRef = useRef<Record<string, string>>({}); const saveInFlight = useRef(false); const flushAgain = useRef(false); const explicitSaveRequested = useRef(false);
  const workspaceRoot = useRef<HTMLElement>(null);
  useEffect(() => { void invoke<WorkspaceData>("load_story_workspace", { id: storyId }).then((next) => { setData(next); try { setLayout(JSON.parse(next.workspaceLayoutJson)); } catch { setLayout(fallbackLayout); } }); }, [storyId]);
  const persistLayout = useCallback((next: Layout) => { window.clearTimeout(layoutTimer.current); layoutTimer.current = window.setTimeout(() => { void invoke("save_workspace_layout", { id: storyId, workspaceLayoutJson: JSON.stringify(next) }); }, 350); }, [storyId]);
  const changeLayout = (next: Layout) => { setLayout(next); persistLayout(next); };
  const flush = useCallback(async (explicit = false) => { const confirmSaved = () => { setSaveState("saved"); window.setTimeout(() => setSaveState("idle"), 1300); }; if (saveInFlight.current) { if (explicit) explicitSaveRequested.current = true; flushAgain.current = true; return; } const entries = Object.entries(dirtyRef.current); if (!entries.length) { if (explicit) confirmSaved(); return; } saveInFlight.current = true; if (explicit) setSaveState("saving"); try { await Promise.all(entries.map(([documentId, markdown]) => invoke("save_markdown_document", { id: storyId, documentId, markdown }))); setDirty((current) => { const remaining = { ...current }; for (const [documentId, markdown] of entries) if (remaining[documentId] === markdown) delete remaining[documentId]; dirtyRef.current = remaining; return remaining; }); if (explicit || explicitSaveRequested.current) { explicitSaveRequested.current = false; confirmSaved(); } } catch { setSaveState("error"); } finally { saveInFlight.current = false; if (flushAgain.current) { flushAgain.current = false; window.setTimeout(() => void flush(), 0); } } }, [storyId]);
  useEffect(() => { dirtyRef.current = dirty; }, [dirty]);
  useEffect(() => { window.clearTimeout(saveTimer.current); if (Object.keys(dirty).length) saveTimer.current = window.setTimeout(() => void flush(), 750); return () => window.clearTimeout(saveTimer.current); }, [dirty, flush]);
  useEffect(() => { const key = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "s") { event.preventDefault(); void flush(true); } if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "f") { event.preventDefault(); setFindOpen(true); } if (event.key === "Escape") setFindOpen(false); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [flush]);
  const documents = useMemo(() => new Map(data?.documents.map((document) => [document.id, document])), [data]);
  const move = (id: string, target: "left" | "right") => { const other = target === "left" ? "right" : "left"; const next = structuredClone(layout); next.left.tabs = next.left.tabs.filter((tab) => tab !== id); next.right.tabs = next.right.tabs.filter((tab) => tab !== id); next[target].tabs.push(id); next[target].activeTabId = id; if (next[other].activeTabId === id) next[other].activeTabId = next[other].tabs[0] ?? null; changeLayout(next); };
  const resize = (boundary: 0 | 1, event: React.PointerEvent<HTMLButtonElement>) => {
    if (layout.collapsed[boundary] || layout.collapsed[boundary + 1] || !workspaceRoot.current) return;
    event.currentTarget.setPointerCapture(event.pointerId);
    const startX = event.clientX; const startSizes = layout.sizes; const width = workspaceRoot.current.getBoundingClientRect().width;
    let newest = layout;
    const movePointer = (nextEvent: PointerEvent) => {
      const delta = (nextEvent.clientX - startX) / width * 100;
      const next = structuredClone(layout); const combined = startSizes[boundary] + startSizes[boundary + 1];
      next.sizes[boundary] = Math.max(15, Math.min(combined - 15, startSizes[boundary] + delta)); next.sizes[boundary + 1] = combined - next.sizes[boundary]; newest = next; setLayout(next);
    };
    const endPointer = () => { window.removeEventListener("pointermove", movePointer); window.removeEventListener("pointerup", endPointer); persistLayout(newest); };
    window.addEventListener("pointermove", movePointer); window.addEventListener("pointerup", endPointer);
  };
  const createDocument = async () => { const title = window.prompt(t(locale, "workspace.newDocumentPrompt")); if (!title?.trim()) return; try { const document = await invoke<Document>("create_markdown_document", { id: storyId, title }); setData((current) => current && { ...current, documents: [...current.documents, document] }); const next = structuredClone(layout); next.left.tabs.push(document.id); next.left.activeTabId = document.id; changeLayout(next); } catch { setSaveState("error"); } };
  if (!data) return <main className="workspace-loading" />;
  return <main className="workspace" ref={workspaceRoot} style={{ gridTemplateColumns: `${layout.collapsed[0] ? "42px" : `${layout.sizes[0]}fr`} 6px ${layout.collapsed[1] ? "42px" : `${layout.sizes[1]}fr`} 6px ${layout.collapsed[2] ? "42px" : `${layout.sizes[2]}fr`}` }}>
    <header className="workspace-bar"><button onClick={onExit} type="button">← {t(locale, "workspace.back")}</button><h1>{data.story.title}</h1><div className={`workspace-save is-${saveState}`} aria-live="polite">{saveState === "saving" ? t(locale, "workspace.saving") : saveState === "saved" ? t(locale, "workspace.saved") : saveState === "error" ? t(locale, "workspace.saveError") : ""}</div><button onClick={() => void createDocument()} type="button">{t(locale, "workspace.newDocument")}</button><button onClick={() => void flush(true)} type="button">{t(locale, "workspace.save")}</button></header>
    <DocumentPanel side="left" locale={locale} layout={layout} documents={documents} dirty={dirty} findOpen={findOpen} query={query} setQuery={setQuery} onChange={(id, markdown) => setDirty((current) => ({ ...current, [id]: markdown }))} onActivate={(id) => changeLayout({ ...layout, left: { ...layout.left, activeTabId: id } })} onMove={move} onToggle={() => { const next = structuredClone(layout); next.collapsed[0] = !next.collapsed[0]; changeLayout(next); }} />
    <button aria-label={t(locale, "workspace.resize")} className="workspace-splitter" onPointerDown={(event) => resize(0, event)} type="button" />
    <DocumentPanel side="right" locale={locale} layout={layout} documents={documents} dirty={dirty} findOpen={findOpen} query={query} setQuery={setQuery} onChange={(id, markdown) => setDirty((current) => ({ ...current, [id]: markdown }))} onActivate={(id) => changeLayout({ ...layout, right: { ...layout.right, activeTabId: id } })} onMove={move} onToggle={() => { const next = structuredClone(layout); next.collapsed[1] = !next.collapsed[1]; changeLayout(next); }} />
    <button aria-label={t(locale, "workspace.resize")} className="workspace-splitter" onPointerDown={(event) => resize(1, event)} type="button" />
    <aside className="tools-panel"><button aria-label={layout.collapsed[2] ? t(locale, "workspace.expand") : t(locale, "workspace.collapse")} className="panel-collapse" onClick={() => { const next=structuredClone(layout); next.collapsed[2]=!next.collapsed[2]; changeLayout(next); }} type="button">{layout.collapsed[2] ? "›" : "‹"}</button>{!layout.collapsed[2] && <><h2>{t(locale, "workspace.tools")}</h2><p>{t(locale, "workspace.empty")}</p></>}</aside>
  </main>;
}

function DocumentPanel({ side, locale, layout, documents, dirty, findOpen, query, setQuery, onChange, onActivate, onMove, onToggle }: { side:"left"|"right"; locale:Locale; layout:Layout; documents:Map<string, Document>; dirty:Record<string,string>; findOpen:boolean; query:string; setQuery:(value:string)=>void; onChange:(id:string,value:string)=>void; onActivate:(id:string)=>void; onMove:(id:string,target:"left"|"right")=>void; onToggle:()=>void }) {
  const panel = layout[side]; const collapsed = layout.collapsed[side === "left" ? 0 : 1]; const active = panel.activeTabId ? documents.get(panel.activeTabId) : undefined; const markdown = active?.id ? dirty[active.id] ?? active.markdown ?? "" : ""; const matches = query ? markdown.match(new RegExp(query.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "gi"))?.length ?? 0 : 0;
  return <section className="document-panel"> <button aria-label={collapsed ? t(locale, "workspace.expand") : t(locale, "workspace.collapse")} className="panel-collapse" onClick={onToggle} type="button">{collapsed ? "›" : "‹"}</button>{!collapsed && <><nav className="document-tabs" aria-label="Documents">{panel.tabs.map((id) => { const doc=documents.get(id); return doc && <button draggable key={id} onClick={() => onActivate(id)} onDragStart={(event) => event.dataTransfer.setData("text/plain", id)} onDoubleClick={() => onMove(id, side === "left" ? "right" : "left")} aria-pressed={id === panel.activeTabId} type="button">{doc.title}</button>; })}</nav>{findOpen && active?.documentType === "markdown" && <label className="workspace-find"><span>{t(locale, "workspace.find")}</span><input autoFocus onChange={(event) => setQuery(event.target.value)} placeholder={t(locale, "workspace.findPlaceholder")} value={query}/><em>{query ? matches ? t(locale, "workspace.matches", { count: matches }) : t(locale, "workspace.noMatches") : ""}</em></label>}<div className="document-body" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); const id=event.dataTransfer.getData("text/plain"); if (id) onMove(id, side); }}>{active?.documentType === "markdown" ? <MarkdownEditor key={active.id} markdown={markdown} onChange={(value) => onChange(active.id, value)} /> : <p>{t(locale, "workspace.empty")}</p>}</div></>}</section>;
}
